server:
  port: 8080

spring:
  application:
    name: api-geteway
  freemarker:
    cache: true
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    allow-session-override: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      number_format: 0.##########
      auto_import: common/common.ftl as common
      template_exception_handler: ignore
      template_update_delay: 0
# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8666/eureka
    register-with-eureka: false                         # api不需要注册到注册中心

# Ribbon 客户端负载均衡配置
#user:
#life-base:
#  ribbon:
#    listOfServer: 127.0.0.1:8083,127.0.0.1:8084

logbook:
  write:
    level: info
  format:
    style: http


file:
  path: /Users/o0u0o/opt/imgs
#  prefix: http://127.0.0.1:8080/images
  prefix: /static/imgs
  #  http://127.0.0.1:8082/static/imgs
domain:
  name: 127.0.0.1:8080

# 配置其他服务
user:
  service:
    name: user
house:
  service:
    name: house
comment:
    service:
      name: comment
