server:
  port: 8085

spring:
  application:
    # 应用名为comment
    name: comment
  datasource:
    #阿里巴巴连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://140.143.181.108:10151/house_comment?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: house_cloud
    password: house_cloud
  druid:
    max-active: 30    # 最大连接数 30
    min-idle: 5       # 最小连接数 5
    max-wait: 10000   # 获取连接的最大等待时间
    validation-query: SELECT 'X'  #解决MySQL8小时问题,默认会提出
    time-between-eviction-runs-millis: 60000  # 空闲连接检查时间间隔
    min-evictable-idle-time-millis: 300000    # 空闲连接最小空闲时间
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 5 #最大连接数为5

eureka:
  client:
    service-url:
      # 注册地址 和eureka-server一致
      defaultZone: http://127.0.0.1:8666/eureka/
    healthcheck:
      enabled: true                                 # 将服务健康状态发送到注册中心
  instance:
    lease-renewal-interval-in-seconds: 5            # 续约心跳间隔时间 5秒
    lease-expiration-duration-in-seconds: 10        # 续约过期时间 10秒 每隔10秒检查一次

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

house:
  service:
    name: house
user:
  service:
    name: user

# 配置logbook #日志级别为info
logbook:
  write:
    level: info
  format:
    style: http
# log4j2配置
logging:
  config: classpath:log4j2.xml