#端口号
server:
  port: 8666

spring:
  application:
    # 应用名eureka-server
    name: eureka-server

# eureka 配置
eureka:
  instance:
    hostname: 127.0.0.1
  server:
    # 留存的服务实例低于50%进入保护模式
    renewal-percent-threshold: 0.5
    # 是否开启保护模式
    enable-self-preservation: true
  client:
    # 是否启用获取注册信息
    fetch-registry: true
    # 是否注册eureka
    register-with-eureka: true
    service-url:
      # 注册和查询都需要依赖该地址，多个以都好分隔
      defaultZone: http://127.0.0.1:${server.port}/eureka/
#      defaultZone: http://local.register.com:${server.port}}/eureka/
