# 加密工具
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

# Eureka配置
eureka:
  client:
    service-url:
      # 注册地址 和eureka-server一致
      defaultZone: http://127.0.0.1:8666/eureka/
    healthcheck:
      # 将服务健康状态发送到注册中心
      enabled: true
  instance:
    # 续约心跳间隔时间 5秒
    lease-renewal-interval-in-seconds: 5
    # 续约过期时间 10秒 每隔10秒检查一次
    lease-expiration-duration-in-seconds: 10